import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { enumeratePnpmGraph, enumerateYarnGraph } from '../src/lockfiles';
import { parseManifest } from '../src/manifest';
import type { Dependency } from '../src/types';

const declared = (): Dependency[] => [
  { name: 'lodash', range: '^4.17.20', dev: false, direct: true },
  { name: '@babel/core', range: '^7.24.0', dev: true, direct: true },
];

// ---- pnpm ----

const PNPM_V9 = `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.20
        version: 4.17.21
    devDependencies:
      '@babel/core':
        specifier: ^7.24.0
        version: 7.24.0(supports-color@9.4.0)
packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-x}
  '@babel/core@7.24.0':
    resolution: {integrity: sha512-y}
  ms@2.1.3:
    resolution: {integrity: sha512-z}
`;

const PNPM_V6 = `lockfileVersion: '6.0'
dependencies:
  lodash:
    specifier: ^4.17.20
    version: 4.17.21
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-x}
  /esbuild@0.19.0:
    resolution: {integrity: sha512-y}
    requiresBuild: true
`;

describe('enumeratePnpmGraph', () => {
  it('pins direct deps from the importer and enumerates transitives (v9, peer suffixes stripped)', () => {
    const deps = enumeratePnpmGraph(PNPM_V9, declared());
    const lodash = deps.find((d) => d.name === 'lodash')!;
    expect(lodash.version).toBe('4.17.21');
    expect(lodash.direct).toBe(true);
    const babel = deps.find((d) => d.name === '@babel/core')!;
    expect(babel.version).toBe('7.24.0'); // (supports-color@…) stripped
    const ms = deps.find((d) => d.name === 'ms')!;
    expect(ms.direct).toBe(false);
    expect(ms.version).toBe('2.1.3');
    expect(deps).toHaveLength(3);
  });

  it('handles v5/v6 top-level sections, /name@version keys and requiresBuild', () => {
    const deps = enumeratePnpmGraph(PNPM_V6, [
      { name: 'lodash', range: '^4.17.20', dev: false, direct: true },
    ]);
    expect(deps.find((d) => d.name === 'lodash')!.version).toBe('4.17.21');
    const esbuild = deps.find((d) => d.name === 'esbuild')!;
    expect(esbuild.direct).toBe(false);
    expect(esbuild.installScript).toBe(true);
  });
});

// ---- yarn ----

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.24.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"
  dependencies:
    ms "^2.1.2"

lodash@^4.17.20, lodash@^4.17.15:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

ms@^2.1.2:
  version "2.1.3"
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."

"lodash@npm:^4.17.20":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"@babel/core@npm:^7.24.0":
  version: 7.24.0
  resolution: "@babel/core@npm:7.24.0"

"ms@npm:^2.1.2":
  version: 2.1.3
  resolution: "ms@npm:2.1.3"
`;

describe('enumerateYarnGraph (v1)', () => {
  it('pins direct deps (multi-spec headers) and enumerates transitives', () => {
    const deps = enumerateYarnGraph(YARN_V1, declared());
    expect(deps.find((d) => d.name === 'lodash')!.version).toBe('4.17.21');
    expect(deps.find((d) => d.name === '@babel/core')!.version).toBe('7.24.0');
    const ms = deps.find((d) => d.name === 'ms')!;
    expect(ms.direct).toBe(false);
    expect(ms.version).toBe('2.1.3');
    expect(deps).toHaveLength(3);
  });
});

describe('enumerateYarnGraph (berry)', () => {
  it('parses the YAML form, strips npm: protocol, skips the workspace self-entry', () => {
    const deps = enumerateYarnGraph(YARN_BERRY, declared());
    expect(deps.find((d) => d.name === 'lodash')!.version).toBe('4.17.21');
    expect(deps.find((d) => d.name === '@babel/core')!.version).toBe('7.24.0');
    expect(deps.find((d) => d.name === 'ms')!.direct).toBe(false);
    expect(deps.find((d) => d.name === 'my-app')).toBeUndefined();
    expect(deps).toHaveLength(3);
  });
});

// ---- discovery precedence through parseManifest ----

describe('parseManifest lockfile discovery', () => {
  const dirs: string[] = [];
  const make = (files: Record<string, string>): string => {
    const dir = mkdtempSync(join(tmpdir(), 'preflight-lock-'));
    dirs.push(dir);
    for (const [name, content] of Object.entries(files)) writeFileSync(join(dir, name), content);
    return dir;
  };
  afterEach(() => {
    for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
  });

  const PKG = JSON.stringify({ dependencies: { lodash: '^4.17.20' } });

  it('expands the graph from pnpm-lock.yaml when that is the lockfile present', () => {
    const dir = make({ 'package.json': PKG, 'pnpm-lock.yaml': PNPM_V6 });
    const m = parseManifest(join(dir, 'package.json'));
    expect(m.lockfile).toBe(true);
    expect(m.dependencies.map((d) => d.name).sort()).toEqual(['esbuild', 'lodash']);
  });

  it('expands the graph from yarn.lock (v1) when that is the lockfile present', () => {
    const dir = make({ 'package.json': PKG, 'yarn.lock': YARN_V1 });
    const m = parseManifest(join(dir, 'package.json'));
    expect(m.lockfile).toBe(true);
    expect(m.dependencies.find((d) => d.name === 'ms')?.direct).toBe(false);
  });

  it('still reports lockfile: false when none exists', () => {
    const dir = make({ 'package.json': PKG });
    expect(parseManifest(join(dir, 'package.json')).lockfile).toBe(false);
  });
});
