import type { Plan } from './plan';
import { runtimeLabel } from './verdict';

// Renders a Plan into starter files: the manifest with compatibility-capped floors
// (commented, where the format allows comments) and a dependabot.yml whose ignore
// rules stop the auto-updater at each runtime boundary / lockstep set.

export interface Artifact {
  filename: string;
  content: string;
}

/** Trim redundant trailing ".0" segments for a readable boundary: "0.40.0" -> "0.40", "9.0.0" -> "9". */
export function trimBoundary(version: string): string {
  let v = version;
  while (/^\d+(\.\d+)+$/.test(v) && v.endsWith('.0')) v = v.slice(0, -2);
  return v;
}

/** requirements.txt (pip) or package.json (npm) with the plan's floors. */
export function renderManifest(plan: Plan): Artifact {
  return plan.ecosystem === 'PyPI' ? renderRequirements(plan) : renderPackageJson(plan);
}

function renderRequirements(plan: Plan): Artifact {
  const lines = [
    `# Generated by \`preflight plan\` — target: ${runtimeLabel(plan.target)}`,
    `# Floors are the newest releases that still install there; caps sit where`,
    `# a release dropped the runtime (mirrored by .github/dependabot.yml ignores).`,
  ];
  const entries = plan.packages.filter((p) => p.floor);
  const main = entries.filter((p) => !p.dev);
  const dev = entries.filter((p) => p.dev);
  const width = Math.max(...entries.map((p) => `${p.name}${p.floor}`.length), 0) + 2;
  const line = (p: (typeof entries)[number], devTag = false) => {
    const spec = `${p.name}${p.floor}`;
    const note = devTag ? `dev · ${p.note}` : p.note;
    return `${spec.padEnd(width)}# ${note}`;
  };
  for (const p of main) lines.push(line(p));
  for (const p of dev) lines.push(line(p, true));
  const missing = plan.packages.filter((p) => !p.floor);
  for (const p of missing) lines.push(`# ${p.name}: ${p.note}`);
  return { filename: 'requirements.txt', content: lines.join('\n') + '\n' };
}

function renderPackageJson(plan: Plan): Artifact {
  const deps: Record<string, string> = {};
  const devDeps: Record<string, string> = {};
  for (const p of plan.packages) {
    if (!p.floor) continue;
    (p.dev ? devDeps : deps)[p.name] = p.floor;
  }
  const json: Record<string, unknown> = {
    // JSON can't carry comments — the per-package notes live in the plan output itself.
    engines: { node: `>=${plan.target.version}` },
    dependencies: deps,
  };
  if (Object.keys(devDeps).length > 0) json.devDependencies = devDeps;
  return { filename: 'package.json', content: JSON.stringify(json, null, 2) + '\n' };
}

/** A dependabot.yml with grouped minor/patch updates + ignore rules at each boundary. */
export function renderDependabot(plan: Plan): Artifact {
  const eco = plan.ecosystem === 'PyPI' ? 'pip' : 'npm';
  const lines = [
    `# Generated by \`preflight plan\` — target: ${runtimeLabel(plan.target)}`,
    'version: 2',
    'updates:',
    `  - package-ecosystem: ${eco}`,
    '    directory: /',
    '    schedule:',
    '      interval: weekly',
    '    groups:',
    '      minor-and-patch:',
    "        patterns: ['*']",
    '        update-types: [minor, patch]',
  ];

  const capped = plan.packages.filter((p) => p.capped && p.firstIncompatible && !p.lockstep.pinned);
  const advice = plan.lockstepAdvice;
  if (capped.length > 0 || advice) {
    lines.push('    ignore:');
  }
  if (capped.length > 0) {
    lines.push(`      # These ranges dropped ${runtimeLabel(plan.target)} — don't bump past them.`);
    for (const p of capped) {
      lines.push(`      - dependency-name: ${quote(p.name)}`);
      lines.push(`        versions: ['>=${trimBoundary(p.firstIncompatible!)}']`);
    }
  }
  if (advice) {
    lines.push(
      `      # ${advice.framework} lockstep set — coordinated by the framework.`,
      `      # Update with \`${advice.tool}\`, not per-package bumps.`,
    );
    for (const name of advice.members) lines.push(`      - dependency-name: ${quote(name)}`);
    for (const prefix of advice.prefixes) lines.push(`      - dependency-name: ${quote(`${prefix}*`)}`);
  }
  return { filename: '.github/dependabot.yml', content: lines.join('\n') + '\n' };
}

/** Quote YAML values that need it (@scoped/* patterns); bare names stay bare. */
function quote(s: string): string {
  return /^[A-Za-z0-9._-]+$/.test(s) ? s : `'${s}'`;
}
